FROM node:22 AS frontend  

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

# stage 2 

FROM nginx:alpine

WORKDIR /app

COPY --from=frontend /app/dist /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
