import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
// eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6IjIyMjE3Y2EyLTUyZTctNDVkNy1hYmM1LTA3OWYwNGM5ZTEyNyIsIm1lZXRpbmdJZCI6ImJiYjg4NDdiLWYyYWQtNDZiNC1hNTkyLTVmMmY2NmUwNmM0ZiIsInBhcnRpY2lwYW50SWQiOiJhYWE1MTc4Ni1kODJmLTQwYTItOTM4Yi00MjdjNmEyYTVmNGUiLCJwcmVzZXRJZCI6ImQ1ZGM3Y2ZjLTlhZDYtNGVkOS05NDE3LTVmNTM3MWY0MWI4YSIsImlhdCI6MTc2NjgyMzc2NSwiZXhwIjoxNzY3NDI4NTY1fQ.LFWEQ2lb1d1gAVTqhCSuk28vn127WDx18I4kXNUhrzMFfibJKEfwcbZz0nt-jM3R7AQuTRGooFXrNdaByQevFE2bSlq5oF7MXeNvtqhAgwPyMpkvRVL-lDIUQBW4cSv5tETKUHboBimqawZguP-p0IQDHXMbZ0vcwVlNcMRAiMxisjVRdmqAmCCTifpzTI8ifSGt_EgxsNoNV3gcDLFFwFagtqepaSzbsOOFbk1GjceCdefVwxTe_DPBOK3qb9fxylUPGRKGdd6jLrUQfrPVyY29wSF0EVjzxGcztWXdJArztxTdYyCM0T6z8NMy3LqX8W1L9IGNyxN-uJmfLj4T3w
createRoot(document.getElementById('root')).render(
    <App />
)
